import { type Producto } from "@apurimeno/contracts";

export const PRODUCTOS_MOCK: Producto[] = [
  {
    id: "prod-001",
    categoriaId: "cat-bebidas",
    nombre: "Agua Mineral sin gas 500ml",
    codigoBarras: "7751234567890",
    precioHuesped: 250,
    precioPublico: 300,
    controlaStock: true,
    stock: 24,
    activo: true,
  },
  {
    id: "prod-002",
    categoriaId: "cat-bebidas",
    nombre: "Agua Mineral con gas 500ml",
    codigoBarras: "7751234567891",
    precioHuesped: 250,
    precioPublico: 300,
    controlaStock: true,
    stock: 15,
    activo: true,
  },
  {
    id: "prod-003",
    categoriaId: "cat-bebidas",
    nombre: "Gaseosa Coca-Cola 500ml",
    codigoBarras: "7750001001234",
    precioHuesped: 400,
    precioPublico: 450,
    controlaStock: true,
    stock: 18,
    activo: true,
  },
  {
    id: "prod-004",
    categoriaId: "cat-snacks",
    nombre: "Galleta Oreo 36g",
    codigoBarras: "7622210987654",
    precioHuesped: 150,
    precioPublico: 200,
    controlaStock: true,
    stock: 30,
    activo: true,
  },
  {
    id: "prod-005",
    categoriaId: "cat-snacks",
    nombre: "Chocolate Sublime 30g",
    codigoBarras: "7613035123456",
    precioHuesped: 200,
    precioPublico: 250,
    controlaStock: true,
    stock: 12,
    activo: true,
  },
  {
    id: "prod-006",
    categoriaId: "cat-snacks",
    nombre: "Papas Nativas Artesanales 50g",
    codigoBarras: null,
    precioHuesped: 350,
    precioPublico: 400,
    controlaStock: true,
    stock: 10,
    activo: true,
  },
  {
    id: "prod-007",
    categoriaId: "cat-aseo",
    nombre: "Kit Dental de Viaje (Cepillo + Pasta)",
    codigoBarras: null,
    precioHuesped: 500,
    precioPublico: 600,
    controlaStock: true,
    stock: 8,
    activo: true,
  },
  {
    id: "prod-008",
    categoriaId: "cat-aseo",
    nombre: "Jabón de Tocador 90g",
    codigoBarras: "7750123456789",
    precioHuesped: 300,
    precioPublico: 350,
    controlaStock: true,
    stock: 14,
    activo: true,
  },
  {
    id: "prod-009",
    categoriaId: "cat-aseo",
    nombre: "Shampoo Sachet 10ml",
    codigoBarras: null,
    precioHuesped: 150,
    precioPublico: 200,
    controlaStock: true,
    stock: 40,
    activo: true,
  },
  {
    id: "prod-010",
    categoriaId: "cat-cafeteria",
    nombre: "Café Pasado en Taza",
    codigoBarras: null,
    precioHuesped: 400,
    precioPublico: 500,
    controlaStock: false,
    stock: 0,
    activo: true,
  },
  {
    id: "prod-011",
    categoriaId: "cat-bebidas",
    nombre: "Cerveza Cusqueña Trigo 330ml",
    codigoBarras: "7750243000125",
    precioHuesped: 800,
    precioPublico: 1000,
    controlaStock: true,
    stock: 0,
    activo: true,
  },
];

export async function obtenerProductos(): Promise<Producto[]> {
  return PRODUCTOS_MOCK;
}
